import Nav from '@/components/Nav'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Tricitie',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main>{ children }</main>
        <Footer />
      </body>
    </html>
  )
}
